Repository vitessio/arewefastyet, pull requests merged in 2021-03, with the labels that each got.

#49 Delete vps
  bench_cli/cli.py
  bench_cli/configuration.py
  docs/cli.md
Labels: Component: CLI, P2, Severity 2, Type: Enhancement

#52 Tasks report zip and upload to S3
  bench_cli/aws.py
  bench_cli/cli.py
  bench_cli/configuration.py
  bench_cli/reporting.py
  bench_cli/run_benchmark.py
  bench_cli/task.py
  bench_cli/zip.py
  docs/cli.md
  requirements.txt
Labels: Component: CLI, Component: Runner, P1, Type: Feature Request

#58 Enable runs on pull request and any commit reference
  ansible/roles/vitess_build/tasks/main.yml
  bench_cli/github_api.py
  bench_cli/task.py
  requirements.txt
  test/unit/bench_cli/test_run_benchmark.py
Labels: Component: Ansible, Component: Runner, Type: Enhancement

#64 Cleaner CLI flag naming convention
  Makefile
  bench_cli/cli.py
  bench_cli/configuration.py
  bench_cli/run_benchmark.py
  config/config_test.yaml
  docs/Installation.md
  docs/cli.md
  test/unit/bench_cli/test_configuration.py
  test/unit/bench_cli/test_run_benchmark.py
Labels: Component: CLI, Type: Enhancement

#67 Enhance cleanup step in BenchmarkRunner
  bench_cli/run_benchmark.py
  bench_cli/task.py
Labels: Component: Runner, Type: Enhancement

#66 Integration of the Ansible Runner library
  .github/workflows/molecule-all.yml
  .gitignore
  bench_cli/reporting.py
  bench_cli/run_benchmark.py
  bench_cli/task.py
  bench_cli/task_oltp.py
  bench_cli/task_tpcc.py
  requirements.txt
  scripts/run-benchmark
  scripts/run-oltp
  scripts/run-tpcc
Labels: Component: Runner, Type: Enhancement

#71 added server module
  go.mod
  go.sum
  go/server/server.go
  go/server/static/css/full-width-pics.css
  go/server/static/css/loader.css
  go/server/static/css/search.css
  go/server/static/vendor/bootstrap/css/bootstrap-grid.css
  go/server/static/vendor/bootstrap/css/bootstrap-grid.css.map
  go/server/static/vendor/bootstrap/css/bootstrap-grid.min.css
  go/server/static/vendor/bootstrap/css/bootstrap-grid.min.css.map
  go/server/static/vendor/bootstrap/css/bootstrap-reboot.css
  go/server/static/vendor/bootstrap/css/bootstrap-reboot.css.map
  go/server/static/vendor/bootstrap/css/bootstrap-reboot.min.css
  go/server/static/vendor/bootstrap/css/bootstrap-reboot.min.css.map
  go/server/static/vendor/bootstrap/css/bootstrap.css
  go/server/static/vendor/bootstrap/css/bootstrap.css.map
  go/server/static/vendor/bootstrap/css/bootstrap.min.css
  go/server/static/vendor/bootstrap/css/bootstrap.min.css.map
  go/server/static/vendor/bootstrap/js/bootstrap.bundle.js
  go/server/static/vendor/bootstrap/js/bootstrap.bundle.js.map
  go/server/static/vendor/bootstrap/js/bootstrap.bundle.min.js
  go/server/static/vendor/bootstrap/js/bootstrap.bundle.min.js.map
  go/server/static/vendor/bootstrap/js/bootstrap.js
  go/server/static/vendor/bootstrap/js/bootstrap.js.map
  go/server/static/vendor/bootstrap/js/bootstrap.min.js
  go/server/static/vendor/bootstrap/js/bootstrap.min.js.map
  go/server/static/vendor/jquery/jquery.js
  go/server/static/vendor/jquery/jquery.min.js
  go/server/static/vendor/jquery/jquery.min.map
  go/server/static/vendor/jquery/jquery.slim.js
  go/server/static/vendor/jquery/jquery.slim.min.js
  go/server/static/vendor/jquery/jquery.slim.min.map
  go/server/templates/footer.tmpl
  go/server/templates/header.tmpl
  go/server/templates/index.tmpl
  go/server/templates/information.tmpl
  go/server/templates/request_benchmark.tmpl
  go/server/templates/search_compare.tmpl
Labels: Component: Web Server, Severity 4

#70 Microbenchmarks: use existing tests
  go.mod
  go.sum
  go/cmd/microbench/microbench.go
  go/cmd/microbench/run.go
  go/cmd/root.go
  go/main.go
  go/mysql/config.go
  go/mysql/config_test.go
  go/mysql/flags.go
  go/mysql/mysql.go
  go/tools/microbench/config.go
  go/tools/microbench/integration/bench_test.go
  go/tools/microbench/line.go
  go/tools/microbench/line_test.go
  go/tools/microbench/microbench.go
  sql/vitess-benchmark.sql
Labels: Type: Feature Request

#77 Addition of sample Equinix Terraform create node
  .gitignore
  infra/terraform/main.tf
  infra/terraform/output.tf
  infra/terraform/variables.tf
  infra/terraform/versions.tf
Labels: Component: Infra, Type: Enhancement

#83 Provision of Equinix devices in the Go CLI
  go.mod
  go.sum
  go/cmd/infra/create.go
  go/cmd/infra/infra.go
  go/cmd/root.go
  go/infra/config.go
  go/infra/config_test.go
  go/infra/equinix/equinix.go
  go/infra/equinix/equinix_test.go
  go/infra/infra.go
Labels: Component: CLI, P0, Type: Feature Request

#85 Specify instance type in Go CLI
  go/infra/equinix/equinix.go
  go/infra/infra.go
  go/infra/infra_test.go
Labels: Component: CLI, Type: Enhancement

#89 Configure infra with Ansible to execute Microbenchmarks
  ansible/microbench.yml
  ansible/microbench_inventory.yml
  ansible/roles/host/tasks/install_deps.yml
  ansible/roles/microbench/defaults/main.yml
  ansible/roles/microbench/tasks/main.yml
  ansible/roles/vitess_build/tasks/install_vitess.yml
Labels: Component: Infra, P0, Type: Enhancement

#90 Link between the Go CLI and WebUI
  .gitignore
  go.mod
  go.sum
  go/cmd/root.go
  go/cmd/web/web.go
  go/server/server.go
  go/server/server_test.go
Labels: Component: CLI, P0, Type: Enhancement

#95 Preprocessing of microbenchmark results and render in web UI
  go/mysql/mysql.go
  go/server/handlers.go
  go/server/mysql.go
  go/server/server.go
  go/server/templates/index.tmpl
  go/server/templates/information.tmpl
  go/server/templates/microbench.tmpl
  go/server/templates/navigation.tmpl
  go/server/templates/request_benchmark.tmpl
  go/server/templates/search_compare.tmpl
  go/tools/microbench/results.go
  go/tools/microbench/results_test.go
Labels: Component: Web Server, P0, Type: Feature Request

#100 try to make numbers easier to read
  go.mod
  go.sum
  go/server/templates/microbench.tmpl
  go/tools/microbench/results.go
  go/tools/microbench/results_test.go
Labels: Component: Web Server, Type: Enhancement

#97 Rolling update server
  .github/workflows/deploy.yml
  supervisor/reverse-proxy.conf
  supervisor/run-ansible.conf
  supervisor/scheduler.conf
  supervisor/server.conf
  supervisor/supervisord.conf
  supervisor/update.sh
Labels: Component: Web Server, GH Actions, P0

#94 Git commit hash in micro benchmark
  go.mod
  go.sum
  go/tools/git/git.go
  go/tools/microbench/microbench.go
Labels: Component: Runner, Type: Enhancement

#101 Destroy terraform infrastructure after running an exec command
  go/cmd/exec/exec.go
  go/exec/exec.go
  go/infra/equinix/equinix.go
  go/infra/infra.go
  go/infra/infra_test.go
Labels: Component: Infra, P0, Type: Enhancement

#106 Addition of unit test and go mod tidy to GitHub Actions workflow
  .github/workflows/golang_build.yaml
  .github/workflows/golang_tidy.yaml
  .github/workflows/golang_unit_test.yaml
  go.sum
Labels: GH Actions, P0, Type: Enhancement

#105 New math package
  go/tools/math/median.go
  go/tools/math/median_test.go
  go/tools/microbench/results.go
  go/tools/microbench/results_test.go
Labels: Type: Enhancement

#107 Addition of Go linter
  .github/workflows/golang_lint.yaml
  dev.env
  go/exec/cmd.go
  go/infra/ansible/ansible.go
  go/infra/ansible/ansible_test.go
  go/infra/ansible/files.go
  go/infra/config.go
  go/infra/config_test.go
  go/infra/equinix/equinix.go
  go/mysql/flags.go
  go/server/server.go
  misc/git/commit-msg
  misc/git/hooks/golangci-lint
  misc/git/pre-commit
Labels: GH Actions, Severity 3
