Repository vitessio/arewefastyet, pull requests merged in 2021-05, with the labels that each got.

#142 Drop test_no column in microbenchmark
  sql/migration/001_New_parent_table_for_executions_125.sql
Labels: Component: Runner, Severity 1, Type: Bug

#143 Adds report subcommand to gen
  .gitignore
  docs/arewefastyet_gen.md
  docs/arewefastyet_gen_report.md
  go.mod
  go.sum
  go/cmd/gen/gen.go
  go/cmd/gen/report/report.go
  go/server/handlers.go
  go/tools/macrobench/compare.go
  go/tools/microbench/compare.go
  go/tools/report/compare_report.go
Labels: Component: Runner, P1, Type: Feature Request

#132 Write prometheus metrics to remote storage
  .github/workflows/golang_lint.yaml
  ansible/macrobench.yml
  docs/arewefastyet_exec.md
  go.sum
  go/exec/cmd.go
  go/exec/exec.go
  go/exec/stats/remote.go
  infra/monitoring/README.md
  infra/monitoring/files/dashboards/compare.json
  infra/monitoring/files/provisioning/ansible.yaml
  infra/monitoring/inventory.yaml
  infra/monitoring/playbook.yaml
  infra/monitoring/roles/common/files/config.cfg
  infra/monitoring/roles/common/tasks/main.yaml
  infra/monitoring/roles/influxdb/tasks/main.yaml
Labels: Component: Infra, P1

#153 Adding Manan to CODEOWNERS
  .github/CODEOWNERS
Labels: GH Actions

#155 Addition of arewefastyet architecture diagram
  README.md
  docs/architecture/arewefastyet_architecture.html
  docs/architecture/arewefastyet_architecture.png
Labels: Component: Infra, Type: Documentation

#158 added foreign key to microbenchmark details
  sql/migration/002_add_foreign_key_to_microbenchmark_details.sql
  sql/migration/test_migration.sh
  sql/vitess-benchmark.sql
Labels: Component: Infra

#144 Query and visualize execution metrics
  docs/arewefastyet_gen_report.md
  docs/arewefastyet_web.md
  go.mod
  go.sum
  go/cmd/gen/report/report.go
  go/cmd/macrobench/run.go
  go/cmd/microbench/run.go
  go/exec/exec.go
  go/exec/metrics/metrics.go
  go/exec/metrics/metrics_test.go
  go/server/handlers.go
  go/server/server.go
  go/server/storage.go
  go/server/templates/compare.tmpl
  go/server/templates/rowMacro.tmpl
  go/server/templates/search.tmpl
  go/storage/influxdb/config.go
  go/storage/influxdb/config_test.go
  go/storage/influxdb/influxdb.go
  go/storage/mysql/config.go
  go/storage/mysql/config_test.go
  go/storage/mysql/flags.go
  go/storage/mysql/mysql.go
  go/tools/macrobench/compare.go
  go/tools/macrobench/config.go
  go/tools/macrobench/macrobench.go
  go/tools/macrobench/results.go
  go/tools/macrobench/results_test.go
  go/tools/math/median.go
  go/tools/math/median_test.go
  go/tools/math/nan.go
  go/tools/microbench/compare.go
  go/tools/microbench/config.go
  go/tools/microbench/line.go
  go/tools/microbench/microbench.go
  go/tools/microbench/results.go
  go/tools/report/compare_report.go
Labels: Component: Runner, P1, Type: Feature Request

#159 Addition of arewefastyet SQL diagram
  README.md
  docs/architecture/sql/arewefastyet_schema.html
  docs/architecture/sql/arewefastyet_schema.png
Labels: Component: Infra, Type: Documentation

#160 Adds descriptive documentation for the command line interface
  docs/README.md
  docs/arewefastyet.md
  docs/arewefastyet_exec.md
  docs/arewefastyet_gen.md
  docs/arewefastyet_gen_doc.md
  docs/arewefastyet_gen_report.md
  docs/arewefastyet_infra.md
  docs/arewefastyet_infra_create.md
  docs/arewefastyet_infra_create_equinix.md
  docs/arewefastyet_macrobench.md
  docs/arewefastyet_macrobench_run.md
  docs/arewefastyet_microbench.md
  docs/arewefastyet_microbench_run.md
  docs/arewefastyet_web.md
  go/cmd/exec/exec.go
  go/cmd/gen/doc/doc.go
  go/cmd/gen/gen.go
  go/cmd/gen/report/report.go
  go/cmd/infra/create.go
  go/cmd/infra/infra.go
  go/cmd/macrobench/macrobench.go
  go/cmd/macrobench/run.go
  go/cmd/microbench/microbench.go
  go/cmd/microbench/run.go
  go/cmd/root.go
  go/cmd/web/web.go
Labels: Component: CLI, Type: Documentation

#164 Add tags and proper name to Equinix Metal instances
  go/exec/exec.go
  go/exec/provision.go
  go/infra/equinix/equinix.go
  go/infra/infra.go
  infra/terraform/main.tf
  infra/terraform/variables.tf
Labels: Component: Infra, P2, Type: Enhancement

#169 Updated documentation with cron jobs
  docs/architecture/arewefastyet_architecture.html
  docs/architecture/arewefastyet_architecture.png
Labels: Component: Infra, Type: Documentation

#172 Remove old execution directories
  infra/cron/cron.sh
  infra/cron/cron.txt
Labels: Component: Infra, Type: Feature Request

#167 Add notification in case of regression
  docs/architecture/sql/arewefastyet_schema.html
  docs/architecture/sql/arewefastyet_schema.png
  docs/arewefastyet_exec.md
  go/exec/cmd.go
  go/exec/exec.go
  go/exec/stats/remote.go
  go/server/cron.go
  go/slack/config.go
  go/slack/slack.go
  go/tools/macrobench/compare.go
  go/tools/macrobench/compare_test.go
  go/tools/microbench/compare.go
  go/tools/microbench/compare_test.go
  sql/migration/001_New_parent_table_for_executions_125.sql
  sql/migration/003_add_type_to_execution.sql
  sql/migration/test_migration.sh
  sql/vitess-benchmark.sql
Labels: Component: Runner, Type: Feature Request

#168 Automate reference and Release Comparisons
  docs/arewefastyet_web.md
  go.mod
  go/exec/exec.go
  go/server/cron.go
  go/server/git.go
  go/server/git_test.go
  go/server/handlers.go
  go/server/server.go
  go/server/server_test.go
  go/server/templates/footer.tmpl
  go/server/templates/header.tmpl
  go/server/templates/microbench.tmpl
  go/server/templates/microbench_single.tmpl
  go/tools/git/git.go
  go/tools/git/git_test.go
  go/tools/microbench/results.go
  go/tools/microbench/results_test.go
Labels: Component: Web Server, Type: Enhancement

#179 Deleted unused api-key parameter in the server
  docs/arewefastyet_web.md
  go/server/server.go
  go/server/server_test.go
Labels: Component: Web Server, P3

#181 Ports tests from testify to quicktest for consistency
  go.mod
  go/tools/git/git_test.go
Labels: Type: Internal

#182 Changed redundant methods and fields naming in the microbench package
  go/cmd/microbench/run.go
  go/exec/exec.go
  go/server/handlers.go
  go/tools/microbench/compare.go
  go/tools/microbench/compare_test.go
  go/tools/microbench/config.go
  go/tools/microbench/line.go
  go/tools/microbench/line_test.go
  go/tools/microbench/microbench.go
  go/tools/microbench/microbench_test.go
  go/tools/microbench/results.go
  go/tools/microbench/results_test.go
  go/tools/report/compare_report.go
Labels: Component: Runner, Type: Enhancement

#183 Adds support to track microbenchmarks as distinct sub-benchmarks
  go/server/handlers.go
  go/server/templates/compare.tmpl
  go/server/templates/microbench.tmpl
  go/server/templates/microbench_single.tmpl
  go/server/templates/search.tmpl
  go/tools/microbench/compare.go
  go/tools/microbench/compare_test.go
  go/tools/microbench/results.go
  go/tools/microbench/results_test.go
  go/tools/report/compare_report.go
Labels: Component: Web Server, Type: Feature Request

#184 Add pull request information in execution and Ansible ExtraVars
  ansible/roles/macrobench/tasks/main.yml
  docs/arewefastyet_exec.md
  go/exec/cmd.go
  go/exec/exec.go
  sql/migration/004_add_pull_request_to_execution.sql
  sql/migration/test_migration.sh
  sql/vitess-benchmark.sql
Labels: Component: Runner, P1, Type: Feature Request

#192 Adds check for master cron job to check if there are existing runs for the same sha
  go/server/cron.go
Labels: Component: Web Server, Type: Bug

#197 Addition of link for comparison in slack message
  go/exec/exec.go
  go/exec/exec_test.go
Labels: Component: Web Server, Type: Enhancement

#196 Updated SQL schema documentation with migration 004
  docs/architecture/sql/arewefastyet_schema.html
  docs/architecture/sql/arewefastyet_schema.png
Labels: Component: Infra, Type: Documentation

#187 Compare MacroBenchmarks of releases like Microbenchmarks
  go/exec/exec.go
  go/server/handlers.go
  go/server/server.go
  go/server/templates/macrobench.tmpl
  go/server/templates/navigation.tmpl
Labels: Component: Web Server, Type: Enhancement

#188 Addition of vitess-mixin dashboards in Grafana
  infra/monitoring/files/dashboards/cluster_overview.json
  infra/monitoring/files/dashboards/keyspace_overview.json
  infra/monitoring/files/provisioning/ansible.yaml
  infra/monitoring/playbook.yaml
Labels: Component: Infra, Type: Enhancement

#195 Removal of old code
  .github/workflows/golang_build.yaml
  .github/workflows/golang_unit_test.yaml
  .github/workflows/pylint-3-7.yml
  .github/workflows/test-oltp.yml
  .github/workflows/test-run-all.yml
  .github/workflows/test-tpcc.yml
  .github/workflows/unit-test-bench-cli.yml
  .github/workflows/verify_cli_documentation.yml
  .gitignore
  Makefile
  bench_cli/__init__.py
  bench_cli/aws.py
  bench_cli/cli.py
  bench_cli/configuration.py
  bench_cli/connection.py
  bench_cli/get_from_remote.py
  bench_cli/get_head_hash.py
  bench_cli/github_api.py
  bench_cli/packet_vps.py
  bench_cli/reporting.py
  bench_cli/run_benchmark.py
  bench_cli/scheduler.py
  bench_cli/server/__init__.py
  bench_cli/server/server.py
  bench_cli/server/templates/index.html
  bench_cli/server/templates/information.html
  bench_cli/server/templates/request_benchmark.html
  bench_cli/server/templates/search_compare.html
  bench_cli/task.py
  bench_cli/task_factory.py
  bench_cli/task_oltp.py
  bench_cli/task_tpcc.py
  bench_cli/zip.py
  docs/Api.md
  docs/Installation.md
  docs/Makefile.md
  docs/README.md
  docs/cli.md
  pictures/erdiagram1.png
  report/sample/sample_oltp.json
  requirements.txt
  setup.py
  test/__init__.py
  test/unit/__init__.py
  test/unit/bench_cli/__init__.py
  test/unit/bench_cli/context.py
  test/unit/bench_cli/test_cli.py
  test/unit/bench_cli/test_configuration.py
  test/unit/bench_cli/test_run_benchmark.py
Labels: P2, Type: Dependencies

#199 Restart cron job after a failure
  docs/arewefastyet_web.md
  go/server/cron.go
  go/server/server.go
Labels: Component: Runner, Type: Feature Request

#204 Use recent and RC tags for macro/micro comparison
  go/tools/git/git.go
  go/tools/git/git_test.go
Labels: Component: Web Server, Type: Enhancement

#200 Always kill devices on execution failure
  go/cmd/exec/exec.go
  go/exec/exec.go
  go/infra/equinix/equinix.go
  go/infra/infra.go
  go/infra/infra_test.go
  go/server/cron.go
Labels: Component: Runner, Severity 1, Type: Enhancement

#205 Patched release tags ordering
  go/server/handlers.go
  go/tools/git/git.go
Labels: Component: Web Server, Type: Bug

#207 Refactor Code
  go/server/handlers.go
  go/tools/git/git.go
  go/tools/git/git_test.go
Labels: Type: Internal

#209 Cron for release branches
  go/server/cron.go
  go/server/handlers.go
  go/tools/git/git.go
  go/tools/git/git_test.go
Labels: Component: Web Server, Type: Feature Request

#210 Addition of a CRON execution pool and job for tags
  go/server/cron.go
Labels: Component: Web Server, Type: Feature Request

#213 Fixing clean up defer statement with new Success method
  go/cmd/exec/exec.go
  go/exec/exec.go
  go/server/cron.go
Labels: Type: Bug

#212 Add release branches to the website
  go/server/handlers.go
Labels: Component: Web Server, Type: Enhancement

#217 Golang memory allocs metrics support
  go/exec/metrics/metrics.go
  go/exec/metrics/metrics_test.go
  go/server/server.go
  go/server/templates/compare.tmpl
  go/server/templates/macrobench.tmpl
  go/server/templates/search.tmpl
  go/tools/macrobench/results_test.go
Labels: Component: Runner, P1, Type: Feature Request

#220 Support for oltp/tpcc vschema and improved equinix tags
  ansible/macrobench.yml
  ansible/macrobench_sharded_inventory.yml
  go/exec/exec.go
  infra/terraform/main.tf
  infra/terraform/variables.tf
  requirements.txt
Labels: Component: Infra, Type: Bug

#222 Planner Version Support in Macrobenchmarks
  ansible/roles/macrobench/tasks/main.yml
  ansible/roles/vtgate/templates/vtgate.conf.j2
  docs/arewefastyet_exec.md
  docs/arewefastyet_macrobench_run.md
  go/exec/cmd.go
  go/exec/exec.go
  go/server/cron.go
  go/tools/macrobench/config.go
  go/tools/macrobench/macrobench.go
  infra/terraform/main.tf
  infra/terraform/variables.tf
  sql/migration/005_add_vtgate_planner_version_to_macrobenchmarks.sql
  sql/migration/test_migration.sh
  sql/vitess-benchmark.sql
Labels: Component: Infra, Type: Feature Request

#223 Use PR's base ref and compare against them
  go/exec/exec.go
  go/server/cron.go
  go/tools/git/github.go
Labels: Component: Runner, Type: Enhancement

#225 Make V3 default and Fix Home page
  go/server/cron.go
  go/server/handlers.go
  go/tools/macrobench/compare.go
  go/tools/macrobench/macrobench.go
  go/tools/macrobench/results.go
Labels: Component: Web Server, Type: Internal

#227 Switch between vtgate planner V3 and Gen4
  go/exec/exec.go
  go/server/handlers.go
  go/server/server.go
  go/server/templates/index.tmpl
  go/server/templates/navigation.tmpl
  go/tools/macrobench/compare.go
  go/tools/report/compare_report.go
Labels: Component: Web Server, Type: Feature Request

#226 V3 vs Gen4 Comparison page
  go/server/handlers.go
  go/server/server.go
  go/server/templates/navigation.tmpl
  go/server/templates/v3VsGen4.tmpl
  go/tools/macrobench/compare.go
Labels: Component: Web Server, Type: Enhancement

#228 Fixing compareSafeComponentMap when left map is empty
  go/exec/metrics/metrics.go
  go/exec/metrics/metrics_test.go
Labels: Component: Runner, Type: Bug

#229 Send Slack notification on every PR execution
  go/exec/exec.go
Labels: Component: Runner, Type: Feature Request

#230 Simpler navigation names
  go/server/templates/navigation.tmpl
Labels: Component: Web Server, Type: Enhancement

#233 Set cookie default instead of warning
  go/server/handlers.go
Labels: Component: Web Server, Type: Bug

#235 Changing InfluxDB default settings for max-series-per-database
  .gitignore
  infra/monitoring/playbook.yaml
  infra/monitoring/roles/influxdb/tasks/main.yaml
Labels: Component: Infra, Type: Bug

#234 More regression runs
  docs/README.md
  docs/arewefastyet_exec.md
  docs/arewefastyet_web.md
  docs/cron.md
  go/exec/cmd.go
  go/exec/exec.go
  go/server/cron.go
  go/server/notification.go
  go/server/notification_test.go
  go/server/server.go
  go/tools/git/git.go
  go/tools/git/github.go
Labels: Component: Web Server, Type: Enhancement

#239 Fixes TestGetAllVitessReleaseCommitHashOrdering
  go/tools/git/git_test.go
Labels: Component: Runner, Type: Bug

#237 Execute With Timeout and enhanced clean up
  go/exec/exec.go
  go/infra/equinix/equinix.go
  go/server/cron.go
Labels: Component: Infra, Type: Enhancement

#236 Benchmarks and E2E test for CompareMacroBenchmarks
  go/storage/influxdb/config.go
  go/tools/macrobench/endtoend/compare_test.go
Labels: Component: Runner, Type: Internal

#242 Fix Cron Jobs
  ansible/roles/macrobench/tasks/main.yml
  ansible/roles/vtgate/templates/vtgate.conf.j2
  docs/arewefastyet_web.md
  go/exec/exec.go
  go/server/cron.go
  go/server/server.go
Labels: Component: Web Server, Type: Enhancement
