Repository vitessio/arewefastyet, pull requests merged in 2021-06, with the labels that each got.

#243 Migration of vitess default branch from master to main
  go/server/cron.go
  go/server/git.go
  go/server/handlers.go
Labels: Component: Infra

#244 UI fixes
  ansible/roles/vitess_build/defaults/main.yml
  go/server/handlers.go
  go/server/server.go
  go/server/templates/compare.tmpl
  go/server/templates/cron.tmpl
  go/server/templates/index.tmpl
  go/server/templates/information.tmpl
  go/server/templates/macrobench.tmpl
  go/server/templates/microbench.tmpl
  go/server/templates/microbench_single.tmpl
  go/server/templates/navigation.tmpl
  go/server/templates/search.tmpl
  go/server/templates/v3VsGen4.tmpl
  go/tools/macrobench/compare.go
  go/tools/microbench/compare.go
  go/tools/microbench/compare_test.go
  go/tools/microbench/results.go
  go/tools/microbench/results_test.go
  go/tools/report/compare_report.go
Labels: Component: Web Server, Type: Enhancement

#245 Changed single microbenchmark table header and year in footer
  go/server/templates/footer.tmpl
  go/server/templates/microbench_single.tmpl
Labels: Component: Web Server, Type: Enhancement

#246 Migration from MySQL to PSDB beta
  docs/arewefastyet_exec.md
  docs/arewefastyet_gen_report.md
  docs/arewefastyet_macrobench_run.md
  docs/arewefastyet_microbench_run.md
  docs/arewefastyet_web.md
  go.mod
  go.sum
  go/cmd/exec/exec.go
  go/cmd/gen/report/report.go
  go/cmd/macrobench/run.go
  go/cmd/microbench/run.go
  go/exec/exec.go
  go/server/server.go
  go/storage/psdb/psdb.go
  go/storage/storage.go
  go/tools/macrobench/compare.go
  go/tools/macrobench/config.go
  go/tools/macrobench/endtoend/compare_test.go
  go/tools/macrobench/macrobench.go
  go/tools/macrobench/results.go
  go/tools/microbench/compare.go
  go/tools/microbench/config.go
  go/tools/microbench/line.go
  go/tools/microbench/microbench.go
  go/tools/microbench/results.go
  go/tools/report/compare_report.go
  sql/migration/006_drop_foreign_key_constraints.sql
  sql/migration/test_migration.sh
  sql/vitess-benchmark.sql
Labels: Component: Runner, P1, Type: Feature Request

#247 Tooltip on gen4 toggle to ease navigation
  go/server/templates/navigation.tmpl
Labels: Component: Web Server, Type: Enhancement

#249 Fixing typo on the website
  go/server/templates/index.tmpl
Labels: Component: Web Server, Type: Enhancement

#252 Upgrading Ansible from 2.9.11 to 2.9.20
  ansible/roles/vitess_build/molecule/all/molecule.yml
  ansible/roles/vitess_build/tasks/mysql.yml
  requirements.txt
Labels: Component: Infra, Type: Dependencies

#251 Addition of tablet_types_to_wait flag to vtgate's configuration
  ansible/roles/vtgate/templates/vtgate.conf.j2
Labels: Component: Runner, P0, Type: Enhancement

#254 Changed the ordering of columns in webserver result tables
  go/server/handlers.go
Labels: Component: Web Server, P2, Type: Enhancement

#255 Update SQL schema documentation
  docs/architecture/sql/arewefastyet_schema.html
  docs/architecture/sql/arewefastyet_schema.png
  sql/migration/test_migration.sh
  sql/vitess-benchmark.sql
Labels: Component: Infra, Type: Documentation

#256 Enable schema tracking in vttablet and vtgate on main cron
  ansible/roles/vtgate/templates/vtgate.conf.j2
  ansible/roles/vttablet/templates/vttablet.conf.j2
  go/exec/exec.go
  go/server/cron.go
Labels: Component: Runner, Type: Enhancement

#257 Fixing v3vsGen4 macro benchmark results graphs order
  go/server/templates/v3VsGen4.tmpl
Labels: Component: Web Server, Type: Bug

#258 Closing rows after select
  go/exec/exec.go
  go/exec/metrics/metrics.go
  go/tools/macrobench/results.go
  go/tools/microbench/results.go
Labels: Component: Web Server, Severity 1, Type: Bug

#259 Addition of a script to migrate execution metrics from influxDB to SQL
  docs/arewefastyet_gen.md
  docs/arewefastyet_gen_exec_metrics.md
  go/cmd/gen/gen.go
  go/cmd/gen/metrics/exec.go
Labels: Component: Runner, Type: Internal

#260 Fixed improved by % for the macrobenchmark errors
  go/tools/macrobench/results.go
  go/tools/macrobench/results_test.go
Labels: Component: Web Server, Type: Bug
